# _config.yml

# Disable default GitHub theme to remove the top link/header
remote_theme: just-the-docs/just-the-docs

just_the_docs:
  logo: "/assets/logo.png"
  nav:
    - title: Home
      url: /
    - title: Privacy Policy
      url: /privacy-policy
    - title: Support
      url: /support

# Basic site metadata
title: Pacer Labs
description: Tools for smarter running. Creators of the Pacer app.

# Custom domain (used for canonical URLs)
url: https://www.pacerlabs.fit

# Exclude unnecessary files from build
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Use GitHub-flavored markdown rendering
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
